# Generated by Django 3.2.9 on 2022-01-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='category',
            field=models.CharField(choices=[('Entertainment', 'Entertainment'), ('Sport', 'Sport'), ('politics', 'politics'), ('fashion', 'fashion'), ('technology', 'technology'), ('bussiness', 'bussiness')], default='Entertainment', max_length=15),
        ),
    ]
