# Generated by Django 3.2.9 on 2022-01-26 13:16

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20220123_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 14, 14, 43, 637443)),
        ),
        migrations.AlterField(
            model_name='title',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
