# Generated by Django 3.2.9 on 2022-01-26 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20220126_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 14, 34, 10, 66031)),
        ),
    ]
