# Generated by Django 3.2.9 on 2022-01-26 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_title_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('body', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='title',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 20, 34, 32, 366226)),
        ),
    ]
