# Generated by Django 3.2.9 on 2022-01-28 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20220128_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='Part',
        ),
        migrations.AlterField(
            model_name='title',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 28, 22, 6, 32, 13426)),
        ),
    ]
