# Generated by Django 3.2.9 on 2022-01-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20220128_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
