# Generated by Django 3.2.9 on 2022-01-29 00:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_title_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='Image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
