# Generated by Django 3.2.9 on 2022-02-01 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20220131_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.title'),
        ),
        migrations.AlterField(
            model_name='title',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
