# Generated by Django 3.2.9 on 2022-02-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20220201_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='category',
            field=models.CharField(choices=[('Entertainment', 'Entertainment'), ('Sport', 'Sport'), ('politics', 'politics'), ('fashion', 'fashion'), ('technology', 'technology'), ('bussiness', 'bussiness')], max_length=30),
        ),
    ]
