# Generated by Django 3.2.9 on 2022-02-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_alter_title_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='Image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
