# Generated by Django 3.2.9 on 2022-02-06 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_alter_comment_part'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
