# Generated by Django 3.2.9 on 2022-02-06 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('body', models.TextField()),
                ('Part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.title')),
            ],
        ),
    ]
