# Generated by Django 3.2.9 on 2022-02-06 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['Date']},
        ),
    ]
