# Generated by Django 4.0.2 on 2022-06-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='Views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
